<h1><center>Titanic survival(svm)</center></h1>


In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

### Loading dataset:

In [5]:

df=pd.read_csv("train.csv")

In [6]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


### Checking null values:

In [8]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### Filling null values:

- dropping cabin column since there are more null values

In [9]:
df.drop('Cabin',axis=1,inplace=True)

- Since,embarked column in object type we can replace null values with mode value

In [10]:
df['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [11]:
df['Embarked'].fillna('S',inplace=True)

- Age can be filled with mean or median

In [12]:
df['Age'].fillna(df['Age'].median(),inplace=True)

-  Checking null values again

In [13]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

### Dropping irrelevant columns:

In [14]:
df.drop(['PassengerId','Name','Ticket'],axis=1,inplace=True)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


### Convert text into categorical:

In [17]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
df['Sex']=lab.fit_transform(df['Sex'])
df['Embarked']=lab.fit_transform(df['Embarked'])

In [18]:
df

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0           0       3    1  22.0      1      0   7.2500         2
1           1       1    0  38.0      1      0  71.2833         0
2           1       3    0  26.0      0      0   7.9250         2
3           1       1    0  35.0      1      0  53.1000         2
4           0       3    1  35.0      0      0   8.0500         2
..        ...     ...  ...   ...    ...    ...      ...       ...
886         0       2    1  27.0      0      0  13.0000         2
887         1       1    0  19.0      0      0  30.0000         2
888         0       3    0  28.0      1      2  23.4500         2
889         1       1    1  26.0      0      0  30.0000         0
890         0       3    1  32.0      0      0   7.7500         1

[891 rows x 8 columns]

<h1><center>SVM</center></h1>


In [36]:
def svm(col):
    x=df.drop([col],axis=1)
    y=df[col]
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
    clf=SVC(gamma=0.01,C=100)
    model=clf.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    print("accuracy score is :",metrics.accuracy_score(y_pred,y_test))
    print("Confusiom matrix is :",confusion_matrix(y_pred,y_test))

### Pclass as dependent variable:

In [37]:
svm('Pclass')

accuracy score is : 0.9106145251396648
Confusiom matrix is : [[44  5  0]
 [ 2 30  6]
 [ 0  3 89]]


### Survived as dependent variable:

In [38]:
svm('Survived')

accuracy score is : 0.7597765363128491
Confusiom matrix is : [[93 26]
 [17 43]]


### Sex as dependent variable:

In [39]:
svm('Sex')

accuracy score is : 0.7486033519553073
Confusiom matrix is : [[39 17]
 [28 95]]


### Embarked as dependent variable:

In [41]:
svm('Embarked')

accuracy score is : 0.7486033519553073
Confusiom matrix is : [[ 19   1  11]
 [  1   2   3]
 [ 19  10 113]]


### Parch as dependent variable:

In [42]:
svm('Parch')

accuracy score is : 0.8324022346368715
Confusiom matrix is : [[130  11   4   0   0   0]
 [  4  10   0   0   0   1]
 [  4   4   9   0   1   0]
 [  0   1   0   0   0   0]
 [  0   0   0   0   0   0]
 [  0   0   0   0   0   0]]
