In [1]:
import numpy as np
from numpy import *

# 1. Create a 3x3x3 array with random values 

In [2]:
arr=np.random.random((3,3,3))
print(arr)
print(arr.shape)

[[[0.41996798 0.96004858 0.5868262 ]
  [0.57426767 0.91828539 0.53078514]
  [0.23696036 0.63140959 0.93412483]]

 [[0.65135285 0.84551452 0.45701571]
  [0.51287947 0.19896548 0.81064197]
  [0.3714872  0.35085623 0.76060496]]

 [[0.43482665 0.11404681 0.16872077]
  [0.60630675 0.2749891  0.34197952]
  [0.7814314  0.20725631 0.77536638]]]
(3, 3, 3)


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
arr=np.eye(5,5)
for i in range(1,5):
    arr[i,i-1]=i
print(arr)
    

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 2. 1. 0. 0.]
 [0. 0. 3. 1. 0.]
 [0. 0. 0. 4. 1.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
x=np.zeros((8,8),dtype=int)
x
x[1::2,::2]=1
x[::2,1::2]=1
x
for i in range(8):
    for j in range(8):
        print(x[i][j],end=" ")
    print()

0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 


# 4. Normalize a 5x5 random matrix

In [5]:
arr=np.random.random((5,5))
print("Intial array is : \n",arr)
norm_arr=arr-arr.min()/arr.max()-arr.min()
print("Normalised array is :\n ",norm_arr)

Intial array is : 
 [[0.95353798 0.9114823  0.70141425 0.77551634 0.10035078]
 [0.96202304 0.47335903 0.52946126 0.29800002 0.94841076]
 [0.84434083 0.09081441 0.20841165 0.27353489 0.60023271]
 [0.28379455 0.02704339 0.56877439 0.35163033 0.65071427]
 [0.17386813 0.52616499 0.14208111 0.3682986  0.30014853]]
Normalised array is :
  [[ 0.89838363  0.85632795  0.64625991  0.72036199  0.04519644]
 [ 0.90686869  0.41820468  0.47430691  0.24284567  0.89325641]
 [ 0.78918648  0.03566006  0.1532573   0.21838054  0.54507836]
 [ 0.2286402  -0.02811096  0.51362004  0.29647598  0.59555992]
 [ 0.11871378  0.47101065  0.08692676  0.31314425  0.24499418]]


# 5.  How to find common values between two arrays?

In [6]:
arr3=array([[1,2,3],[4,5,6],[7,8,9]])
arr4=array([[2,4,6],[8,10,12],[0,14,16]])
print("first array is :",arr3)
print("second array is :",arr4)
x=np.intersect1d(arr3,arr4)
print("common values between 2 arrays are :",x)

first array is : [[1 2 3]
 [4 5 6]
 [7 8 9]]
second array is : [[ 2  4  6]
 [ 8 10 12]
 [ 0 14 16]]
common values between 2 arrays are : [2 4 6 8]


# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
from datetime import date,timedelta
today=date.today()
yesterday=today-timedelta(days=1)
tomorrow=today+timedelta(days=1)
print("today's date is",today)
print("yesterday's date is",yesterday)
print("tomorrow's date is",tomorrow)

today's date is 2020-07-27
yesterday's date is 2020-07-26
tomorrow's date is 2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [8]:
arr1=array([[2,3,4],[4,5,6],[7,8,9]])
arr2=array([[5,6,7],[4,11,12],[13,14,15]])
print(arr1)
print(arr2)
arr1==arr2

[[2 3 4]
 [4 5 6]
 [7 8 9]]
[[ 5  6  7]
 [ 4 11 12]
 [13 14 15]]


array([[False, False, False],
       [ True, False, False],
       [False, False, False]])

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [9]:
vect=np.random.random(10)
print("Intial vector is :",vect)
vect[vect.argmax()]=0
print("after replacing with 0 :")
print(vect)

Intial vector is : [0.39762477 0.44250004 0.77128075 0.93801158 0.97929842 0.48312567
 0.66250546 0.54916639 0.33262095 0.21070555]
after replacing with 0 :
[0.39762477 0.44250004 0.77128075 0.93801158 0.         0.48312567
 0.66250546 0.54916639 0.33262095 0.21070555]


# 9. How to print all the values of an array?

In [10]:
arr5=array([[2,3,4],[5,6,7],[8,9,10]])
for i in arr5:
    for j in i:
        print(j,end=" ")

2 3 4 5 6 7 8 9 10 

# 10.Subtract the mean of each row of a matrix

In [11]:
arr6=array([[2,3,4],[5,6,7],[10,11,12]])
print("before subtraction array is",arr6)
arr6=arr6-arr6.mean(axis=1)
arr6.astype(dtype=int)
print("after subtracting the mean of each row of a matrix:",arr6.astype(dtype=int))

before subtraction array is [[ 2  3  4]
 [ 5  6  7]
 [10 11 12]]
after subtracting the mean of each row of a matrix: [[-1 -3 -7]
 [ 2  0 -4]
 [ 7  5  1]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [12]:
vet1 = array([10,20,30,40,50,60,70,80,90,10])
print("Original vector : ")
print(vet1,"\n")
vet2 = array([0,6,8,6])                  #given indices   in vetor 2

for i in np.unique(vet2):                #iterate only on unique indices to avoid multiple time addition
    vet1[i] = vet1[i] + 1
    
    
print("After adding 1 to given indices :")
print(vet1)

Original vector : 
[10 20 30 40 50 60 70 80 90 10] 

After adding 1 to given indices :
[11 20 30 40 50 60 71 80 91 10]


# 12.How to get the diagonal of a dot product?

In [13]:
v=array([[1,2,3],[4,5,6],[7,8,9]])
u=array([[10,11,12],[13,14,15],[16,17,18]])
w=v.dot(u)
print(w)
print("diagonal of a dot product is :",diagonal(w))

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
diagonal of a dot product is : [ 84 216 366]


# 13.How to find the most frequent value in an array?

In [14]:
arr7=array([2,3,4,4,5,6,6,7,8,9,4,3,1,2])
print("most frequent value is :")
freq=(np.bincount(arr7).argmax())
freq

most frequent value is :


4

# 14.How to get the n largest values of an array

In [15]:
arr10=array([2,4,10,12,15,17,15,20,25,32])
print("given array is : \n",arr10)
new=np.unique(arr10)
new1=np.sort(new)
print(new1)
n = int(input("Enter the n value : "))
print("\nThe",n,"largest values of given array are :")
print(new1[-n:])

given array is : 
 [ 2  4 10 12 15 17 15 20 25 32]
[ 2  4 10 12 15 17 20 25 32]
Enter the n value : 2

The 2 largest values of given array are :
[25 32]


# 15.How to create a record array from a regular array?

In [91]:
arr1=array([1,2,3,4])
arr2=array(['apple','cherry','mango','orange'])
arr3=array(['harika','charan','bittu','lasya'])
print("Array1 =",arr1,"\nArray2 =",arr2,"\nArray3=",arr3)
result=np.core.records.fromarrays([arr1,arr2,arr3])
print("Recorded array is \n ",result)

Array1 = [1 2 3 4] 
Array2 = ['apple' 'cherry' 'mango' 'orange'] 
Array3= ['harika' 'charan' 'bittu' 'lasya']
Recorded array is 
  [(1, 'apple', 'harika') (2, 'cherry', 'charan') (3, 'mango', 'bittu')
 (4, 'orange', 'lasya')]
